ex/butlair/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views
from log.forms import LoginForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('log.urls')),
    url(r'^login/$', views.login, {'template_name': 'log/login.html', 'authentication_form': LoginForm}),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),
    #url(r'^tours/',include('tours.urls')),
]


if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

log/urls.py
from django.conf.urls import url,include
from . import views

# We are adding a URL called /home
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^tours/',include('tours.urls')),
    url(r'^rests/',include('search_engine.urls')),
    url(r'^shopping/',include('shopping.urls')),
    url(r'^cafe_bars/',include('cafe_bars.urls')),
    
]

myapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views
from log.forms import LoginForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('log.urls')),
    url(r'^login/$', views.login, {'template_name': 'log/login.html', 'authentication_form': LoginForm}),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),
    #url(r'^tours/',include('tours.urls')),
]


if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_engine/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^$',views.index,name='index'),
    #url(r'^thanks/$',views.index,name='index'),
    #url(r'^insert$',views.index_ins,name='insert_ins'),
    url(r'^insert/$',views.index_ins,name='index_ins'),
    url(r'^results/$',views.index,name='index'),
    
]

ex/login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

ex/search_engine/models.py
from __future__ import unicode_literals
from math import radians, cos, sin, asin, sqrt
from django.db import models

# Create your models here.


class Rests(models.Model):
    PRICE_CHOICES = (
        ("-10","ews 10 eurw"),
        ("10-20","10 me 20 eurw"),
        ("20-30","20 me 30 eurw"),
        ("30-40","30 me 40 eurw"),
        ("40-50","40 me 50 eurw"),
        ("50-","50 eurw kai panw")
        )

    name = models.CharField(max_length=128, unique=False)
    perioxh=models.CharField(max_length=128, unique=False,blank=True)
    periferia=models.CharField(max_length=128, unique=False,blank=True)
    dieuthinsh=models.CharField(max_length=128, unique=False,blank=True)
    price=models.CharField(max_length=30, unique=False,blank=True,choices=PRICE_CHOICES)
    live_mousikh=models.NullBooleanField()
    for_kids=models.NullBooleanField()
    view=models.NullBooleanField()
    romantic=models.NullBooleanField()
    cozy=models.NullBooleanField()
    stigma=models.URLField(blank=True)
    butlair_link=models.URLField(blank=True)
    site=models.URLField(blank=True)
    e_table=models.NullBooleanField()
    thl=models.CharField(max_length=128, unique=False,blank=True)
    comments=models.TextField(blank=True)
    rate=models.FloatField(null=True,blank=True)
    latitude = models.FloatField(null=True,blank=True)
    longitude = models.FloatField(null=True,blank=True)

    
    def __unicode__(self):
        #data=[self.name,self.perioxh]
        data=self.id
        return data

    
    def distance(self,lon1,lat1):
        lon2=self.longitude
        lat2=self.latitude
        lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
        # haversine formula 
        dlon = lon2 - lon1 
        dlat = lat2 - lat1 
        a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
        c = 2 * asin(sqrt(a)) 
        km = 6367 * c
        return km
 



class Bar_Restaurant(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)
    def __unicode__(self):
        data=self.name.id
        return data
    
class Brunch(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data
#########Street Food#######################

class Souvlaki(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Falafes(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data
    
class Lagmatzoun(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Sandwitch(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Krepa(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Kotompoukies(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Mpougatsa_Sfoliata(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Burger(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data
##################################################################

class Mezedopoleia(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Fusion(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Ellhnikh_Paradosiakh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Burger_Amerikanikh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Vegeterian(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Fish(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Mesogeiakh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Sigxronh_Ellhnikh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Indikh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Gallikh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data
    
class Italikh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Multi_Ethnic(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Afrikanikh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Sushi(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Ispanikh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Latin(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Sigxronh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Politikh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

class Asiatikh(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Glyko(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data


class Pagwto(models.Model):
    name=models.ForeignKey(Rests, on_delete=models.CASCADE)

    def __unicode__(self):
        data=self.name.id
        return data

    


    






    



    






    



    







    



    

















    

    


    

    


    

    


    


    



    



    


    



    


    




    













    

login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

ex/search_engine/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import *

class search(forms.Form):
        onoma = forms.CharField(label='Αναζήτηση Μαγαζιού', max_length=100,required=False,widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))



class Search_bar(forms.Form):
        perioxh = forms.CharField(label='Περιοχή', max_length=100,required=False,widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
        


class Aktina(forms.Form):
        aktina = forms.FloatField(label='Ακτίνα',required=False,widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))



class lat_lon(forms.Form):        
        lat = forms.FloatField(label='latitude',required=False)
        lon = forms.FloatField(label='longitude',required=False)

class Kouzines(forms.Form):
        bar_restaurant = forms.BooleanField(label='Bar Restaurant',required=False)
        brunch = forms.BooleanField(label='Brunch',required=False)
        mezedopoleia = forms.BooleanField(label='Μεζεδοπολεία',required=False)
        fusion = forms.BooleanField(label='Fusion',required=False)
        ellhnikh_paradosiakh = forms.BooleanField(label='Ελληνική Παραδοσιακή',required=False)
        vegeterian = forms.BooleanField(label='Vegeterian',required=False)
        fish = forms.BooleanField(label='Ψάρι',required=False)
        mesogeiakh = forms.BooleanField(label='Μεσογειακή',required=False)
        sigxronh_ellinikh = forms.BooleanField(label='Σύγχρονη Ελληνική',required=False)
        multi_ethnic = forms.BooleanField(label='Multi Ethnic',required=False)
        sigxronh = forms.BooleanField(label='Σύγχρονη',required=False)
        gliko = forms.BooleanField(label='Γλυκό',required=False)
        pagwto = forms.BooleanField(label='Παγωτό',required=False)
        international = forms.BooleanField(label='Διεθνείς',required=False)
        street_food = forms.BooleanField(label='Street Food',required=False)


class International(forms.Form):
        burger_amerikanikh = forms.BooleanField(label='Burger-Αμερικάνικη',required=False)
        ispanikh = forms.BooleanField(label='Ισπανική',required=False)
        italikh = forms.BooleanField(label='Ιταλική',required=False)
        sushi = forms.BooleanField(label='Sushi',required=False)
        afrikanikh = forms.BooleanField(label='Αφρικάνικη',required=False)
        politikh = forms.BooleanField(label='Πολίτικη',required=False)
        indikh = forms.BooleanField(label='Ινδική',required=False)
        gallikh = forms.BooleanField(label='Γαλλική',required=False)
        latin = forms.BooleanField(label='Λάτιν',required=False)
        asiatikh = forms.BooleanField(label='Ασιατική',required=False)



class Street_Food(forms.Form):
        souvlaki = forms.BooleanField(label='Σουβλάκι',required=False)
        falafes = forms.BooleanField(label='Φαλάφελ',required=False)
        lagmatzoun = forms.BooleanField(label='Λαγματζούν',required=False)
        sandwitch = forms.BooleanField(label='Σάντουϊτς',required=False)
        krepa = forms.BooleanField(label='Κρέπα',required=False)
        kotompoukies = forms.BooleanField(label='Κοτομπουκιές',required=False)
        mpougatsa_sfoliata = forms.BooleanField(label='Μπουγάτσα-Σφολιάτα',required=False)
        burger = forms.BooleanField(label='Burger',required=False)
        

class Loipa(forms.Form):
        live_music=forms.BooleanField(label='Ζωντανή Μουσική',required=False)
        for_kids=forms.BooleanField(label='Κατάλληλο Για Παιδιά',required=False)
        view=forms.BooleanField(label='Όμορφο Τοπίο',required=False)
        romantic=forms.BooleanField(label='Ρομαντικό',required=False)
        #xwris_filtro=forms.BooleanField(label='Χωρίς Φίλτρο',required=False)

class Timh(forms.Form):
        deka=forms.BooleanField(label='Έως 10 ευρώ',required=False)
        deka_eikosi=forms.BooleanField(label='10-20',required=False)
        eikosi_trianta=forms.BooleanField(label='20-30',required=False)
        trianta_saranta=forms.BooleanField(label='30-40',required=False)
        saranta_peninta=forms.BooleanField(label='40-50',required=False)
        peninta_kai=forms.BooleanField(label='50 και πάνω',required=False)
        #lefta_yparxoun=forms.BooleanField(label='Χωρίς Φίλτρο',required=False)

class Onoma(forms.Form):
       onoma = forms.CharField(label='Όνομα', max_length=100,required=True)

class Perioxh(forms.Form):
        perioxh = forms.CharField(label='Περιοχή', max_length=100,required=False)

class Dieuthinsh(forms.Form):
        dieuthinsh=forms.CharField(label='Διεύθυνση', max_length=100,required=True)


class Perifereia(forms.Form):
        perifereia=forms.CharField(label='Περιφέρεια', max_length=100,required=False)


class ins(forms.ModelForm):
        class Meta:
            model = Rests
            fields=['id','dieuthinsh','longitude','latitude','name','perioxh','periferia','price','live_mousikh','for_kids','view','romantic','cozy','site','e_table','thl','rate','butlair_link','stigma','comments']
        




class NameForm(forms.Form):
    
        your_name = forms.CharField(label='Search', max_length=100)
        what_for = forms.BooleanField(label='Souvlaki',required=False)


class NameForm2(forms.Form):
    
        your_name = forms.CharField(label='Your name', max_length=100)
        what_for = forms.BooleanField(label='Souvlaki',required=False)

ex/login/views.py
from django.shortcuts import render

# Create your views here.

login/views.py
from django.shortcuts import render

# Create your views here.

ex/search_engine/templates/search_engine/foods.html
<!DOCTYPE html>
<html lang="en">

<head> 
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-7" /> 
  <title>Butlair</title> 
  <script src="http://maps.google.com/maps/api/js?sensor=false" 
          type="text/javascript"></script>
		  
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>	
		{% load staticfiles %}
	<link href="{% static 'search_engine/css/bootstrap.min.css' %}" rel="stylesheet">	  
	
	<style>
		.navbar-default {
    background-color: red;
    border-color: #030033;
	
	#header {
			background-color:black;
			color:white;
			text-align:center;
			padding:5px;
		}
		
		#section {
			width:1200px;
			float:center;
			padding:0px;
		}
		#footer {
			background-color:black;
			color:white;
			clear:both;
			text-align:center;
			padding:5px;
		}
		
		hr { 
			display: block;
			margin-top: 0.5em;
			margin-bottom: 0.5em;
			margin-left: auto;
			margin-right: auto;
			border-style: inset;
			border-width: 3px;
			border-color:grey;
		} 
		figcaption { 
					display: block;
					text-align:center;
		}
	
		.row + .row {
				border-top:0;
				padding-right:20px;
				border-left:20px;
			}
	
	
}
</style>





	
</head> 

<body>
                    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Butlair</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="/rests/">Restaurants</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/tours/">Tours</a></li>
            <li><a href="#">Shopping</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/logout/">Log Out</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

                {% block content %}
                {% endblock %}


                    <!-- Core Scripts - Include with every page -->
                    <script src = "{% static 'log/js/jquery.min.js' %}"></script>
                    <script src = "{% static 'log/js/bootstrap.min.js' %}"></script>
        {% block javascript %}
        {% endblock %}


            </body>

</html>
	

ex/search_engine/templates/search_engine/home.html
{% extends "log/base.html" %}

{% block content %}

 
		
<h2 align="center">What doesn't kill you.... eat it!!!</h2>

<div class="container">
<form action="/rests/results/" method="post" id="sub" >
    {% csrf_token %}
	<div class="row">
	<div class="col-xs-6 col-md-4">
	{{ form0 }}
	</div>
	<div class="col-xs-6 col-md-4">
    {{ form1 }}
	</div>
	<div class="col-xs-6 col-md-4">
	{{ form8 }}
	</div>
	<div id="lat_lon">
	{{ form7 }}
	</div>
	</div>
	<hr>
	<h4>Είδος κουζίνας:</h4>
	{{ form2 }}
	<hr>
	<div id="vr">
	<h4>Street Food:</h4>
	{{ form3 }}
	</div>
	<div id="dieth">
	<h4>Διεθνείς:</h4>
	{{ form6 }}
	</div>
	<hr>
	<h4>Εύρος Τιμής:</h4>
	{{ form4 }}
	<hr>
	<h4>Εxtra:</h4>
	{{ form5 }}
	<hr>
 	
</form>
<button id="test" class="btn btn-success btn-block" width= 250px >Για να δούμε τι θα βρούμε...</button>

</div>

<script type="text/javascript">
		
		$("#vr").hide();
		$("#dieth").hide();
		$("#lat_lon").hide();
		
		var map;
		
		document.getElementById("test").onclick = function() {myFunction()};
		
		function myFunction(){
			
			if($("#id_onoma").val()){document.forms["sub"].submit();}


			else{
				var myLatLng = {lat: 0, lng: 0};
				var latitude,longitude;
				var geocoder = new google.maps.Geocoder();
				var address = $("#id_perioxh").val();
				var marker;
				
				geocoder.geocode( { 'address': address}, function(results, status) {

				if (status == google.maps.GeocoderStatus.OK) {
					latitude = results[0].geometry.location.lat();
					longitude = results[0].geometry.location.lng();
					$("#id_lat").val(latitude);
					$("#id_lon").val(longitude);
					myLatLng.lat=latitude; 
					myLatLng.lng=longitude;
					document.forms["sub"].submit();	
					
					
					
					
					}
					}); 
					
				}
				
				
			}
	


	$(document).ready(function(){
    $("#id_street_food").click(function(){
        $("#vr").toggle();
    });
});

	$(document).ready(function(){
    $("#id_international").click(function(){
        $("#dieth").toggle();
    });
});




</script>
				
	



		
{% endblock %}

ex/search_engine/templates/search_engine/insert.html
{% extends "search_engine/foods.html" %}

{% block content %}
		
<p>Hey fuck off!!</p>
<p></p>
<button id="test">find</button>
<form action="/vaggelis/insert/" method="post">
    {% csrf_token %}
    {{ form1.as_ul }}
	<p> </p>
	{{ form2 }}
	<p> </p>
	{{ form3 }}
	<p> </p>
    <input type="submit" value="Submit" />

	
	
</form>

<div id="map" style="width: 500px; height: 400px;"></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">
		
		var map;
		
		document.getElementById("test").onclick = function() {myFunction()};
		
		function myFunction(){
			
				
				var myLatLng = {lat: 0, lng: 0};
				var latitude,longitude;
				var geocoder = new google.maps.Geocoder();
				var address = $("#id_dieuthinsh").val();
				var marker;
				
				geocoder.geocode( { 'address': address}, function(results, status) {

				if (status == google.maps.GeocoderStatus.OK) {
					latitude = results[0].geometry.location.lat();
					longitude = results[0].geometry.location.lng();
					$("#id_latitude").val(latitude);
					$("#id_longitude").val(longitude);
					myLatLng.lat=latitude; 
					myLatLng.lng=longitude;
					map = new google.maps.Map(document.getElementById('map'), {
					zoom: 15,
					center: new google.maps.LatLng(myLatLng),
					mapTypeId: google.maps.MapTypeId.ROADMAP
					});
					var marker = new google.maps.Marker({
					position: myLatLng,
					map: map,
					title: 'hello'
					});			
					
					
					
					}
					}); 
						
				}
</script>	
{% endblock %}

ex/search_engine/templates/search_engine/results.html
{% extends "log/base.html" %}

{% block content %}



		
<h2 align="center">What doesn't kill you.... eat it!!!</h2>
<div class="container">
<form action="/rests/results/" method="post" id="sub" >
    {% csrf_token %}
	<div class="row">
	<div class="col-xs-6 col-md-4">
	{{ form0 }}
	</div>
	<div class="col-xs-6 col-md-4">
    {{ form1 }}
	</div>
	<div class="col-xs-6 col-md-4">
	{{ form8 }}
	</div>
	<div id="lat_lon">
	{{ form7 }}
	</div>
	</div>
	<hr>
	<h4>Είδος κουζίνας:</h4>
	{{ form2 }}
	<hr>
	<div id="vr">
	<h4>Street Food:</h4>
	{{ form3 }}
	</div>
	<div id="dieth">
	<h4>Διεθνείς:</h4>
	{{ form6 }}
	</div>
	<hr>
	<h4>Εύρος Τιμής:</h4>
	{{ form4 }}
	<hr>
	<h4>Εxtra:</h4>
	{{ form5 }}
	<hr>
 	
</form>
<button id="test" class="btn btn-success btn-block" width= 250px >Για να δούμε τι θα βρούμε...</button>
<hr>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
	
<div class="container" id="map" style="height: 400px;" align="center" ></div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">


	
	var map;
	var address;
	var locations = {{ stigma|safe }}
	var myLatLng = {lat: {{ lat|safe }}, lng: {{ lon|safe }}};
    
    map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: new google.maps.LatLng(myLatLng),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, i;
	
	for (i = 0; i < locations.length; i++) {  
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
   

	document.getElementById("test").onclick = function() {myFunction()};
		
		function myFunction(){
			
			if($("#id_onoma").val()){document.forms["sub"].submit();}
			
			else{
				var latitude,longitude;
				var geocoder = new google.maps.Geocoder();
				address = $("#id_perioxh").val();
				var marker;
				
				geocoder.geocode( { 'address': address}, function(results, status) {

				if (status == google.maps.GeocoderStatus.OK) {
					latitude = results[0].geometry.location.lat();
					longitude = results[0].geometry.location.lng();
					$("#id_lat").val(latitude);
					$("#id_lon").val(longitude);
					myLatLng.lat=latitude; 
					myLatLng.lng=longitude;
					document.forms["sub"].submit();
					
					
			
					}
					}); 
							
				}
		
			}	
		

if(document.getElementById('id_street_food').checked==false){
			$("#vr").hide();
			}
		
if(document.getElementById('id_international').checked==false){
			$("#dieth").hide();
			}		
	
		$("#lat_lon").hide();	
		
$("#lat_lon").hide();
		$(document).ready(function(){
    $("#id_street_food").click(function(){
        $("#vr").toggle();
    });
});

	$(document).ready(function(){
    $("#id_international").click(function(){
        $("#dieth").toggle();
    });
});	
			
			
				
</script>


	
		<table class="table table-condensed" style="width:40%">
				<tr>
					<td class="active">#</td>
					<td class="active">Όνομα Μαγαζιού</td>
					<td class="active">Περιοχή</td>
					<td class="active">Ιστοσελίδα</td>
				</tr>	
			{% for c in detail %}
				<tr>
					<td class="success">{{ c.id }}</td>
					<td class="danger">{{ c.name }}</td>
					<td class="success">{{ c.perioxh }}</td>
					<td class="danger"><a href= "{{ c.site }}"> {{ c.site }}</a></td>
					
				</tr>
			{% endfor %}
		</table>

</div>		
{% endblock %}